package com.cater.constants;

/**
 * Description: 
 * Created: Nov 23, 2014
 * @author Hari 
 */
public enum Cuisines {
	AMERICAN, CHINESE, CONTINENTAL, CUBAN, FRENCH, GREEK, INDIAN, INDONESIAN, ITALIAN, JAPANESE, KOREAN, LEBANESE, MALAYSIAN, MEXICAN, RUSSIAN, SINGAPORE, SPANISH, THAI, TIBETAN, VIETNAMESE;
}
