package com.cater.constants;

public enum QuoteStatus {
	CREATED, RESTAURANT_SUBMITTED_PRICE, RESTAURANT_UPDATED_PRICE, CUSTOMER_UPDATED_MENU, CUSTOMER_UPDATED_BUDGET, APPROVED, DENIED, PAID, CUSTOMER_ORDER_CONFIRMED
}
