-- DELETE ENTRIES
DELETE FROM Quote;
DELETE FROM Menu;
DELETE FROM Event;
DELETE FROM Customer;
DELETE FROM Restaurant;
DELETE FROM Address;
DELETE FROM Login;

-- DROP TABLES
DROP TABLE Quote;
DROP TABLE Menu;
DROP TABLE Event;
DROP TABLE Customer;
DROP TABLE Restaurant;
DROP TABLE Address;
DROP TABLE Login;
